# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/cron"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/mailhog"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/mariadb"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/newrelic-daemon"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/nginx-proxy"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47


  - package-ecosystem: "docker"
    directory: "/php/7.4"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/php/8.0"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/php/8.1"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/php/8.2"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/php/8.3"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/php/8.4"
    ignore:
      - dependency-name: "php"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/php/stable"
    ignore:
      - dependency-name: "php"
        update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/postfix"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47

  - package-ecosystem: "docker"
    directory: "/redis"
    schedule:
      interval: "weekly"
    reviewers:
      - mrrobot47
