FROM mcuadros/ofelia@sha256:9478fec5cbcbad325c01b3d76523d44ebccb7f62c153c1389335a0a46f05c58e
LABEL org.label-schema.schema-version="1.0.0-rc1"
LABEL org.label-schema.vendor="EasyEngine"
LABEL org.label-schema.name="cron"
